# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [43]:
import torch

Construct a 5x3 matrix, uninitialized:

In [44]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.5980e+33,  9.4868e-43,  3.0737e+00],
        [ 5.0642e+00,  2.4475e+00,  7.6000e-01],
        [ 1.1320e+00,  1.8180e-01,  1.5118e+00],
        [ 1.0525e+00,  1.5475e+00,  8.1761e-01],
        [ 1.7956e+00,  5.4406e-01,  7.1739e-01]])


Construct a randomly initialized matrix:

In [45]:
x = torch.rand(5, 3) # value range 0-1
print(x)

tensor([[0.8418, 0.9378, 0.5188],
        [0.6750, 0.5273, 0.5188],
        [0.1160, 0.7080, 0.1607],
        [0.1042, 0.5597, 0.9020],
        [0.1148, 0.6043, 0.6833]])


  Construct a matrix filled zeros and of dtype `int64`:

In [46]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [47]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [48]:
x = x.new_ones(5, 3)      # new_* methods take in sizes; inherit data type and device if not specified
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.0064,  1.1038, -1.1221],
        [-0.6044, -1.9079,  1.0631],
        [-1.0360,  0.2058, -1.7392],
        [ 1.6823, -0.1641,  1.1703],
        [-0.5903, -0.2164,  0.9260]])


Get its size:

In [49]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [50]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3418,  1.7026, -0.6113],
        [-0.2424, -1.5191,  1.3174],
        [-0.8264,  0.6904, -1.4599],
        [ 1.8659,  0.5775,  1.6514],
        [ 0.0785,  0.7806,  1.1504]])


Addition: syntax 2

In [51]:
print(torch.add(x, y))

tensor([[ 1.3418,  1.7026, -0.6113],
        [-0.2424, -1.5191,  1.3174],
        [-0.8264,  0.6904, -1.4599],
        [ 1.8659,  0.5775,  1.6514],
        [ 0.0785,  0.7806,  1.1504]])


Addition: providing an output tensor as argument

In [52]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3418,  1.7026, -0.6113],
        [-0.2424, -1.5191,  1.3174],
        [-0.8264,  0.6904, -1.4599],
        [ 1.8659,  0.5775,  1.6514],
        [ 0.0785,  0.7806,  1.1504]])


Addition: in-place

In [53]:
# adds x to y
y.add_(x)
print(y)

# or
y += x
print(y)

tensor([[ 1.3418,  1.7026, -0.6113],
        [-0.2424, -1.5191,  1.3174],
        [-0.8264,  0.6904, -1.4599],
        [ 1.8659,  0.5775,  1.6514],
        [ 0.0785,  0.7806,  1.1504]])
tensor([[ 2.3482,  2.8063, -1.7335],
        [-0.8467, -3.4270,  2.3805],
        [-1.8623,  0.8962, -3.1991],
        [ 3.5481,  0.4134,  2.8217],
        [-0.5117,  0.5641,  2.0763]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [54]:
print(x[:, 1])

tensor([[ 1.0064,  1.1038, -1.1221],
        [-0.6044, -1.9079,  1.0631],
        [-1.0360,  0.2058, -1.7392],
        [ 1.6823, -0.1641,  1.1703],
        [-0.5903, -0.2164,  0.9260]])
tensor([ 1.0064, -0.6044, -1.0360,  1.6823, -0.5903])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [62]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [63]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9347])
-0.9346919655799866


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [64]:
a = torch.ones(5)
print(a)

tensor([1, 1, 1, 1, 1])


In [58]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [59]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [60]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [61]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!